name: Generate and Deploy Viewer

on:
  schedule:
    - cron: '55 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    # ===============================================================
    # vvvvvvvvvvvvvvvvvv 這是本次最關鍵的修改 vvvvvvvvvvvvvvvvvvv
    # 明確地給予這個 job 寫入儲存庫內容的權限
    permissions:
      contents: write
    # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    # ===============================================================
    
    runs-on: ubuntu-latest

    steps:
      # 步驟 1: 下載儲存庫的程式碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步驟 2: 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 步驟 3: 安裝依賴
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      # 步驟 4: 執行 Python 腳本來產生 token.json
      - name: Generate token file
        env:
          APS_CLIENT_ID: ${{ secrets.APS_CLIENT_ID }}
          APS_CLIENT_SECRET: ${{ secrets.APS_CLIENT_SECRET }}
        run: python generate_token.py

      # 步驟 5: 將 viewer 資料夾部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./viewer
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "chore: Auto-refresh APS token and deploy"